### ISSUE TITLE
h2 and quote buttons change the styling of the unselected next line

### ISSUE THREAD

**Issue by halilb** [chrisdavies/minidoc#18] opened 2021-03-05 20:13 UTC
Here is the video about it:

https://user-images.githubusercontent.com/2227041/110168417-3a6d1e80-7e08-11eb-971f-2d04124cb97d.mov

It happens with list buttons as well.

**Comment by chrisdavies** [comment] 2021-03-05 21:43
Also can't reproduce this one!

**Comment by chrisdavies** [comment] 2021-03-10 13:50
I think this was fixed with the recent commits. Closing until further notice.

**Closed by chrisdavies** 2021-03-10 13:50 UTC
